import aqueduct from '@/assets/icons/buildings/aqueduct.png'
import ar from '@/assets/icons/buildings/ar.png'
import barracks from '@/assets/icons/buildings/barracks.png'
import blacksmith from '@/assets/icons/buildings/blacksmith.png'
import cattleRanch from '@/assets/icons/buildings/cattle-ranch.png'
import cistern from '@/assets/icons/buildings/cistern.png'
import dock from '@/assets/icons/buildings/dock.png'
import farm from '@/assets/icons/buildings/farm.png'
import farmhouse from '@/assets/icons/buildings/farmhouse.png'
import forge from '@/assets/icons/buildings/forge.png'
import ger from '@/assets/icons/buildings/ger.png'
import granary from '@/assets/icons/buildings/granary.png'
import house from '@/assets/icons/buildings/house.png'
import how from '@/assets/icons/buildings/how.png'
import hc from '@/assets/icons/buildings/hunting-cabin.png'
import keep from '@/assets/icons/buildings/keep.png'
import lc from '@/assets/icons/buildings/lc.png'
import market from '@/assets/icons/buildings/market.png'
import mc from '@/assets/icons/buildings/mc.png'
import mercenaryHouse from '@/assets/icons/buildings/mercenary-house.png'
import militarySchool from '@/assets/icons/buildings/military-school.png'
import mill from '@/assets/icons/buildings/mill.png'
import monastery from '@/assets/icons/buildings/monastery.png'
import mosque from '@/assets/icons/buildings/mosque.png'
import oliveGrove from '@/assets/icons/buildings/olive-grove.png'
import outpost from '@/assets/icons/buildings/outpost.png'
import ovoo from '@/assets/icons/buildings/ovoo.png'
import pagoda from '@/assets/icons/buildings/pagoda.png'
import palisadeGate from '@/assets/icons/buildings/palisade-gate.png'
import palisade from '@/assets/icons/buildings/palisade.png'
import pasture from '@/assets/icons/buildings/pasture.png'
import pitMine from '@/assets/icons/buildings/pit.png'
import shintoShrine from '@/assets/icons/buildings/shinto-shrine.png'
import siege from '@/assets/icons/buildings/siege.png'
import stable from '@/assets/icons/buildings/stable.png'
import stoneGate from '@/assets/icons/buildings/stone-gate.png'
import tc from '@/assets/icons/buildings/tc.png'
import tollOutpost from '@/assets/icons/buildings/toll-outpost.png'
import tower from '@/assets/icons/buildings/tower.png'
import university from '@/assets/icons/buildings/university.png'
import village from '@/assets/icons/buildings/village.png'
import wall from '@/assets/icons/buildings/wall.png'
import woodenFortress from '@/assets/icons/buildings/wooden-fortress.png'

export enum BuildingType {
  ECO = 'ECO',
  MILITARY = 'MILITARY',
  RESEARCH = 'RESEARCH',
  FORTIFIED = 'FORTIFIED',
}
export enum BuildingAge {
  I = 'I',
  II = 'II',
  III = 'III',
  IV = 'IV',
}
export enum BuildingCivGroup {
  GENERIC = 'GENERIC',
  COMMON = 'COMMON',
  MONGOL = 'MONGOL',
  RUS = 'RUS',
  CHINESE = 'CHINESE',
  ABBASID = 'ABBASID',
  DELHI = 'DELHI',
  MALIANS = 'MALIANS',
  OTTOMANS = 'OTTOMANS',
  JAPANESE = 'JAPANESE',
  BYZANTINES = 'BYZANTINES',
}
export interface Building {
  name: string
  shortcut: [number, number]
  icon: string
  type: BuildingType
  age: BuildingAge
  group: BuildingCivGroup
}
const Buildings = [
  // Age I
  {
    name: 'House',
    shortcut: [0, 0],
    icon: house,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.GENERIC,
  },
  {
    name: 'Mill',
    shortcut: [0, 1],
    icon: mill,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.GENERIC,
  },
  {
    name: 'Lumber Camp',
    shortcut: [0, 2],
    icon: lc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.GENERIC,
  },
  {
    name: 'Mining Camp',
    shortcut: [0, 3],
    icon: mc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.GENERIC,
  },
  {
    name: 'Farm',
    shortcut: [0, 4],
    icon: farm,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.GENERIC,
  },
  {
    name: 'Barracks',
    shortcut: [0, 5],
    icon: barracks,
    type: BuildingType.MILITARY,
    age: BuildingAge.I,
    group: BuildingCivGroup.COMMON,
  },
  {
    name: 'Dock',
    shortcut: [0, 6],
    icon: dock,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.COMMON,
  },
  {
    name: 'Outpost',
    shortcut: [0, 8],
    icon: outpost,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.GENERIC,
  },
  {
    name: 'Palisade Wall',
    shortcut: [0, 9],
    icon: palisade,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.GENERIC,
  },
  {
    name: 'Palisade Gate',
    shortcut: [0, 10],
    icon: palisadeGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.GENERIC,
  },
  // Age II
  {
    name: 'Blacksmith',
    shortcut: [1, 0],
    icon: blacksmith,
    type: BuildingType.RESEARCH,
    age: BuildingAge.II,
    group: BuildingCivGroup.COMMON,
  },
  {
    name: 'Market',
    shortcut: [1, 1],
    icon: market,
    type: BuildingType.ECO,
    age: BuildingAge.II,
    group: BuildingCivGroup.COMMON,
  },
  {
    name: 'Town Center',
    shortcut: [1, 2],
    icon: tc,
    type: BuildingType.ECO,
    age: BuildingAge.II,
    group: BuildingCivGroup.COMMON,
  },
  {
    name: 'Archery Range',
    shortcut: [1, 4],
    icon: ar,
    type: BuildingType.MILITARY,
    age: BuildingAge.II,
    group: BuildingCivGroup.COMMON,
  },
  {
    name: 'Stable',
    shortcut: [1, 5],
    icon: stable,
    type: BuildingType.MILITARY,
    age: BuildingAge.II,
    group: BuildingCivGroup.GENERIC,
  },
  {
    name: 'Stone Tower',
    shortcut: [1, 8],
    icon: tower,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.GENERIC,
  },
  {
    name: 'Stone Wall',
    shortcut: [1, 9],
    icon: wall,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.GENERIC,
  },
  {
    name: 'Stone Gate',
    shortcut: [1, 10],
    icon: stoneGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.GENERIC,
  },
  // Age III
  {
    name: 'Monastery',
    shortcut: [2, 0],
    icon: monastery,
    type: BuildingType.RESEARCH,
    age: BuildingAge.III,
    group: BuildingCivGroup.GENERIC,
  },
  {
    name: 'Siege Workshop',
    shortcut: [2, 4],
    icon: siege,
    type: BuildingType.MILITARY,
    age: BuildingAge.III,
    group: BuildingCivGroup.COMMON,
  },
  {
    name: 'Keep',
    shortcut: [2, 8],
    icon: keep,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.III,
    group: BuildingCivGroup.GENERIC,
  },
  // Age IV
  {
    name: 'University',
    shortcut: [3, 0],
    icon: university,
    type: BuildingType.RESEARCH,
    age: BuildingAge.IV,
    group: BuildingCivGroup.GENERIC,
  },
  /**
   * Mongol-specific
   */
  {
    name: 'Ovoo',
    shortcut: [0, 0],
    icon: ovoo,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.MONGOL,
  },
  {
    name: 'Ger',
    shortcut: [0, 1],
    icon: ger,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.MONGOL,
  },
  {
    name: 'Pasture',
    shortcut: [0, 4],
    icon: pasture,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.MONGOL,
  },
  {
    name: 'Outpost',
    shortcut: [0, 8],
    icon: outpost,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.MONGOL,
  },
  // Stable in Age I
  {
    name: 'Stable',
    shortcut: [0, 7],
    icon: stable,
    type: BuildingType.MILITARY,
    age: BuildingAge.I,
    group: BuildingCivGroup.MONGOL,
  },
  {
    name: 'Monastery',
    shortcut: [2, 0],
    icon: monastery,
    type: BuildingType.RESEARCH,
    age: BuildingAge.III,
    group: BuildingCivGroup.MONGOL,
  },
  /**
   * Rus-specific
   */
  {
    name: 'House',
    shortcut: [0, 0],
    icon: house,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.RUS,
  },
  {
    name: 'Hunting Cabin',
    shortcut: [0, 1],
    icon: hc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.RUS,
  },
  {
    name: 'Lumber Camp',
    shortcut: [0, 2],
    icon: lc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.RUS,
  },
  {
    name: 'Mining Camp',
    shortcut: [0, 3],
    icon: mc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.RUS,
  },
  {
    name: 'Farm',
    shortcut: [0, 4],
    icon: farm,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.RUS,
  },
  {
    name: 'Fortress',
    shortcut: [0, 8],
    icon: woodenFortress,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.RUS,
  },
  {
    name: 'Palisade Wall',
    shortcut: [0, 9],
    icon: palisade,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.RUS,
  },
  {
    name: 'Palisade Gate',
    shortcut: [0, 10],
    icon: palisadeGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.RUS,
  },
  {
    name: 'Stable',
    shortcut: [1, 5],
    icon: stable,
    type: BuildingType.MILITARY,
    age: BuildingAge.II,
    group: BuildingCivGroup.RUS,
  },
  {
    name: 'Monastery',
    shortcut: [2, 0],
    icon: monastery,
    type: BuildingType.RESEARCH,
    age: BuildingAge.III,
    group: BuildingCivGroup.RUS,
  },
  {
    name: 'Stone Tower',
    shortcut: [1, 8],
    icon: tower,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.RUS,
  },
  {
    name: 'Stone Wall',
    shortcut: [1, 9],
    icon: wall,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.RUS,
  },
  {
    name: 'Stone Gate',
    shortcut: [1, 10],
    icon: stoneGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.RUS,
  },
  {
    name: 'Keep',
    shortcut: [2, 8],
    icon: keep,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.III,
    group: BuildingCivGroup.RUS,
  },
  {
    name: 'University',
    shortcut: [3, 0],
    icon: university,
    type: BuildingType.RESEARCH,
    age: BuildingAge.IV,
    group: BuildingCivGroup.RUS,
  },
  /**
   * Chinese-specific
   */
  {
    name: 'House',
    shortcut: [0, 0],
    icon: house,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'Mill',
    shortcut: [0, 1],
    icon: mill,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'Lumber Camp',
    shortcut: [0, 2],
    icon: lc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'Mining Camp',
    shortcut: [0, 3],
    icon: mc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'Farm',
    shortcut: [0, 4],
    icon: farm,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'Outpost',
    shortcut: [0, 8],
    icon: outpost,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'Palisade Wall',
    shortcut: [0, 9],
    icon: palisade,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'Palisade Gate',
    shortcut: [0, 10],
    icon: palisadeGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'Stable',
    shortcut: [1, 5],
    icon: stable,
    type: BuildingType.MILITARY,
    age: BuildingAge.II,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'Village',
    shortcut: [0, 7],
    icon: village,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'Stone Tower',
    shortcut: [1, 8],
    icon: tower,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'Stone Wall',
    shortcut: [1, 9],
    icon: wall,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'Stone Gate',
    shortcut: [1, 10],
    icon: stoneGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'Monastery',
    shortcut: [2, 0],
    icon: monastery,
    type: BuildingType.RESEARCH,
    age: BuildingAge.III,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'Granary',
    shortcut: [1, 6],
    icon: granary,
    type: BuildingType.ECO,
    age: BuildingAge.II,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'Keep',
    shortcut: [2, 8],
    icon: keep,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.III,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'University',
    shortcut: [3, 0],
    icon: university,
    type: BuildingType.RESEARCH,
    age: BuildingAge.IV,
    group: BuildingCivGroup.CHINESE,
  },
  {
    name: 'Pagoda',
    shortcut: [2, 5],
    icon: pagoda,
    type: BuildingType.ECO,
    age: BuildingAge.III,
    group: BuildingCivGroup.CHINESE,
  },
  /**
   * Abbasid-specific
   */
  {
    name: 'House',
    shortcut: [0, 0],
    icon: house,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.ABBASID,
  },
  {
    name: 'Mill',
    shortcut: [0, 1],
    icon: mill,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.ABBASID,
  },
  {
    name: 'Lumber Camp',
    shortcut: [0, 2],
    icon: lc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.ABBASID,
  },
  {
    name: 'Mining Camp',
    shortcut: [0, 3],
    icon: mc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.ABBASID,
  },
  {
    name: 'Farm',
    shortcut: [0, 4],
    icon: farm,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.ABBASID,
  },
  {
    name: 'House of Wisdom',
    shortcut: [0, 7],
    icon: how,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.ABBASID,
  },
  {
    name: 'Outpost',
    shortcut: [0, 8],
    icon: outpost,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.ABBASID,
  },
  {
    name: 'Palisade Wall',
    shortcut: [0, 9],
    icon: palisade,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.ABBASID,
  },
  {
    name: 'Palisade Gate',
    shortcut: [0, 10],
    icon: palisadeGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.ABBASID,
  },
  {
    name: 'Stable',
    shortcut: [1, 5],
    icon: stable,
    type: BuildingType.MILITARY,
    age: BuildingAge.II,
    group: BuildingCivGroup.ABBASID,
  },
  {
    name: 'Stone Tower',
    shortcut: [1, 8],
    icon: tower,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.ABBASID,
  },
  {
    name: 'Stone Wall',
    shortcut: [1, 9],
    icon: wall,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.ABBASID,
  },
  {
    name: 'Stone Gate',
    shortcut: [1, 10],
    icon: stoneGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.ABBASID,
  },
  {
    name: 'Prayer Tent',
    shortcut: [2, 0],
    icon: mosque,
    type: BuildingType.ECO,
    age: BuildingAge.III,
    group: BuildingCivGroup.ABBASID,
  },
  {
    name: 'Keep',
    shortcut: [2, 8],
    icon: keep,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.III,
    group: BuildingCivGroup.ABBASID,
  },
  {
    name: 'University',
    shortcut: [3, 0],
    icon: university,
    type: BuildingType.RESEARCH,
    age: BuildingAge.IV,
    group: BuildingCivGroup.ABBASID,
  },
  /**
   * Delhi-specific
   */
  {
    name: 'House',
    shortcut: [0, 0],
    icon: house,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.DELHI,
  },
  {
    name: 'Mill',
    shortcut: [0, 1],
    icon: mill,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.DELHI,
  },
  {
    name: 'Lumber Camp',
    shortcut: [0, 2],
    icon: lc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.DELHI,
  },
  {
    name: 'Mining Camp',
    shortcut: [0, 3],
    icon: mc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.DELHI,
  },
  {
    name: 'Farm',
    shortcut: [0, 4],
    icon: farm,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.DELHI,
  },
  {
    name: 'Mosque',
    shortcut: [0, 7],
    icon: mosque,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.DELHI,
  },
  {
    name: 'Outpost',
    shortcut: [0, 8],
    icon: outpost,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.DELHI,
  },
  {
    name: 'Palisade Wall',
    shortcut: [0, 9],
    icon: palisade,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.DELHI,
  },
  {
    name: 'Palisade Gate',
    shortcut: [0, 10],
    icon: palisadeGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.DELHI,
  },
  {
    name: 'Stable',
    shortcut: [1, 5],
    icon: stable,
    type: BuildingType.MILITARY,
    age: BuildingAge.II,
    group: BuildingCivGroup.DELHI,
  },
  {
    name: 'Stone Tower',
    shortcut: [1, 8],
    icon: tower,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.DELHI,
  },
  {
    name: 'Stone Wall',
    shortcut: [1, 9],
    icon: wall,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.DELHI,
  },
  {
    name: 'Stone Gate',
    shortcut: [1, 10],
    icon: stoneGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.DELHI,
  },
  {
    name: 'Keep',
    shortcut: [2, 8],
    icon: keep,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.III,
    group: BuildingCivGroup.DELHI,
  },
  {
    name: 'University',
    shortcut: [3, 0],
    icon: university,
    type: BuildingType.RESEARCH,
    age: BuildingAge.IV,
    group: BuildingCivGroup.DELHI,
  },
  /**
   * Malian-specific
   */
  {
    name: 'House',
    shortcut: [0, 0],
    icon: house,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.MALIANS,
  },
  {
    name: 'Mill',
    shortcut: [0, 1],
    icon: mill,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.MALIANS,
  },
  {
    name: 'Lumber Camp',
    shortcut: [0, 2],
    icon: lc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.MALIANS,
  },
  {
    name: 'Mining Camp',
    shortcut: [0, 3],
    icon: mc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.MALIANS,
  },
  {
    name: 'Farm',
    shortcut: [0, 4],
    icon: farm,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.MALIANS,
  },
  {
    name: 'Pit Mine',
    shortcut: [0, 7],
    icon: pitMine,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.MALIANS,
  },
  {
    name: 'Toll Outpost',
    shortcut: [0, 8],
    icon: tollOutpost,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.MALIANS,
  },
  {
    name: 'Palisade Wall',
    shortcut: [0, 9],
    icon: palisade,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.MALIANS,
  },
  {
    name: 'Palisade Gate',
    shortcut: [0, 10],
    icon: palisadeGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.MALIANS,
  },
  {
    name: 'Stable',
    shortcut: [1, 5],
    icon: stable,
    type: BuildingType.MILITARY,
    age: BuildingAge.II,
    group: BuildingCivGroup.MALIANS,
  },
  {
    name: 'Cattle Ranch',
    shortcut: [1, 6],
    icon: cattleRanch,
    type: BuildingType.ECO,
    age: BuildingAge.II,
    group: BuildingCivGroup.MALIANS,
  },
  {
    name: 'Stone Tower',
    shortcut: [1, 8],
    icon: tower,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.MALIANS,
  },
  {
    name: 'Stone Wall',
    shortcut: [1, 9],
    icon: wall,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.MALIANS,
  },
  {
    name: 'Stone Gate',
    shortcut: [1, 10],
    icon: stoneGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.MALIANS,
  },
  {
    name: 'Mosque',
    shortcut: [2, 0],
    icon: mosque,
    type: BuildingType.ECO,
    age: BuildingAge.III,
    group: BuildingCivGroup.MALIANS,
  },
  {
    name: 'Keep',
    shortcut: [2, 8],
    icon: keep,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.III,
    group: BuildingCivGroup.MALIANS,
  },
  {
    name: 'University',
    shortcut: [3, 0],
    icon: university,
    type: BuildingType.RESEARCH,
    age: BuildingAge.IV,
    group: BuildingCivGroup.MALIANS,
  },
  /**
   * Ottoman-specific
   */
  {
    name: 'House',
    shortcut: [0, 0],
    icon: house,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.OTTOMANS,
  },
  {
    name: 'Mill',
    shortcut: [0, 1],
    icon: mill,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.OTTOMANS,
  },
  {
    name: 'Lumber Camp',
    shortcut: [0, 2],
    icon: lc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.OTTOMANS,
  },
  {
    name: 'Mining Camp',
    shortcut: [0, 3],
    icon: mc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.OTTOMANS,
  },
  {
    name: 'Farm',
    shortcut: [0, 4],
    icon: farm,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.OTTOMANS,
  },
  {
    name: 'Military School',
    shortcut: [0, 7],
    icon: militarySchool,
    type: BuildingType.MILITARY,
    age: BuildingAge.I,
    group: BuildingCivGroup.OTTOMANS,
  },
  {
    name: 'Outpost',
    shortcut: [0, 8],
    icon: outpost,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.OTTOMANS,
  },
  {
    name: 'Palisade Wall',
    shortcut: [0, 9],
    icon: palisade,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.OTTOMANS,
  },
  {
    name: 'Palisade Gate',
    shortcut: [0, 10],
    icon: palisadeGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.OTTOMANS,
  },
  {
    name: 'Stable',
    shortcut: [1, 5],
    icon: stable,
    type: BuildingType.MILITARY,
    age: BuildingAge.II,
    group: BuildingCivGroup.OTTOMANS,
  },
  {
    name: 'Stone Tower',
    shortcut: [1, 8],
    icon: tower,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.OTTOMANS,
  },
  {
    name: 'Stone Wall',
    shortcut: [1, 9],
    icon: wall,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.OTTOMANS,
  },
  {
    name: 'Stone Gate',
    shortcut: [1, 10],
    icon: stoneGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.OTTOMANS,
  },
  {
    name: 'Mosque',
    shortcut: [2, 0],
    icon: mosque,
    type: BuildingType.ECO,
    age: BuildingAge.III,
    group: BuildingCivGroup.OTTOMANS,
  },
  {
    name: 'Keep',
    shortcut: [2, 8],
    icon: keep,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.III,
    group: BuildingCivGroup.OTTOMANS,
  },
  {
    name: 'University',
    shortcut: [3, 0],
    icon: university,
    type: BuildingType.RESEARCH,
    age: BuildingAge.IV,
    group: BuildingCivGroup.OTTOMANS,
  },
  /**
   * Japanese-specific
   */
  {
    name: 'Farmhouse',
    shortcut: [0, 0],
    icon: farmhouse,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.JAPANESE,
  },
  {
    name: 'Lumber Camp',
    shortcut: [0, 2],
    icon: lc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.JAPANESE,
  },
  {
    name: 'Forge',
    shortcut: [0, 3],
    icon: forge,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.JAPANESE,
  },
  {
    name: 'Farm',
    shortcut: [0, 4],
    icon: farm,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.JAPANESE,
  },
  {
    name: 'Outpost',
    shortcut: [0, 8],
    icon: outpost,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.JAPANESE,
  },
  {
    name: 'Palisade Wall',
    shortcut: [0, 9],
    icon: palisade,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.JAPANESE,
  },
  {
    name: 'Palisade Gate',
    shortcut: [0, 10],
    icon: palisadeGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.JAPANESE,
  },
  {
    name: 'Stable',
    shortcut: [1, 5],
    icon: stable,
    type: BuildingType.MILITARY,
    age: BuildingAge.II,
    group: BuildingCivGroup.JAPANESE,
  },
  {
    name: 'Stone Tower',
    shortcut: [1, 8],
    icon: tower,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.JAPANESE,
  },
  {
    name: 'Stone Wall',
    shortcut: [1, 9],
    icon: wall,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.JAPANESE,
  },
  {
    name: 'Stone Gate',
    shortcut: [1, 10],
    icon: stoneGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.JAPANESE,
  },
  {
    name: 'Shinto Shrine / Buddhist Temple',
    shortcut: [2, 0],
    icon: shintoShrine,
    type: BuildingType.ECO,
    age: BuildingAge.III,
    group: BuildingCivGroup.JAPANESE,
  },
  {
    name: 'University',
    shortcut: [3, 0],
    icon: university,
    type: BuildingType.RESEARCH,
    age: BuildingAge.IV,
    group: BuildingCivGroup.JAPANESE,
  },
  {
    name: 'Castle',
    shortcut: [3, 4],
    icon: keep,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.IV,
    group: BuildingCivGroup.JAPANESE,
  },
  /**
   * Byzantine-specific
   */
  {
    name: 'House',
    shortcut: [0, 0],
    icon: house,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'Mill',
    shortcut: [0, 1],
    icon: mill,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'Lumber Camp',
    shortcut: [0, 2],
    icon: lc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'Mining Camp',
    shortcut: [0, 3],
    icon: mc,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'Olive Grove',
    shortcut: [0, 4],
    icon: oliveGrove,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'Cistern',
    shortcut: [0, 7],
    icon: cistern,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'Outpost',
    shortcut: [0, 8],
    icon: outpost,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'Palisade Wall',
    shortcut: [0, 9],
    icon: palisade,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'Palisade Gate',
    shortcut: [0, 10],
    icon: palisadeGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.I,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'Aqueduct',
    shortcut: [0, 11],
    icon: aqueduct,
    type: BuildingType.ECO,
    age: BuildingAge.I,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'Stable',
    shortcut: [1, 5],
    icon: stable,
    type: BuildingType.MILITARY,
    age: BuildingAge.II,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'Mercenary House',
    shortcut: [1, 6],
    icon: mercenaryHouse,
    type: BuildingType.MILITARY,
    age: BuildingAge.II,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'Stone Tower',
    shortcut: [1, 8],
    icon: tower,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'Stone Wall',
    shortcut: [1, 9],
    icon: wall,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'Stone Gate',
    shortcut: [1, 10],
    icon: stoneGate,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.II,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'Monastery',
    shortcut: [2, 0],
    icon: monastery,
    type: BuildingType.ECO,
    age: BuildingAge.III,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'Keep',
    shortcut: [2, 8],
    icon: keep,
    type: BuildingType.FORTIFIED,
    age: BuildingAge.III,
    group: BuildingCivGroup.BYZANTINES,
  },
  {
    name: 'University',
    shortcut: [3, 0],
    icon: university,
    type: BuildingType.RESEARCH,
    age: BuildingAge.IV,
    group: BuildingCivGroup.BYZANTINES,
  },
] satisfies Building[]

export default Buildings
